site_name: 'EI Metrics'
site_description: ' A knowledge management system for the metrics service line'
site_author: 'Erik Anderson'
copyright: 'Copyright &copy; 2019 Erik Anderson'

#Configuration
theme: 
  name: material
  favicon: 'img/ei-logo-black.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/ei-logo-white.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

# Navigation
nav:
- Home: 'index.md'
- Metrics Services:
  - 'How We Work': 'metrics-services/how-we-work.md'
- Metrics Design Philosophy:
  - 'Overview': 'metrics-design/overview.md'
  - 'Step 1: Start at the End': 'metrics-design/step1-start-at-the-end.md'
  - 'Step 2: Map It': 'metrics-design/step2-map-it.md'
  - 'Step 3: Develop Empathy': 'metrics-design/step3-develop-empathy.md'
  - 'Step 4: Define the Problem': 'metrics-design/step4-define-the-problem.md'
  - 'Step 5: Identify a Solution': 'metrics-design/step5-identify-a-solution.md'
  - 'Step 6: Implement': 'under-construction.md'
  - 'Step 7: Iterate & Adapt': 'under-construction.md'
- Project Organization:
  - 'Project Planning': 'project-planning/project-planning.md'
- Git:
  - 'Create Project': 'git/initializing-git.md'
- Data Management:
  - 'Database Overview': 'data-management/database-overview.md'
- Spatial Analysis:
  - 'Spatial Analysis Overview': 'under-construction.md'
  - 'Land Use Land Cover Tutorial': 'spatial-analysis/lulc-tutorial/lulc-tutorial.md'
- Additional Resources:
  - 'Persona Development Guide': 'additional-resources/persona-guide.md'
  - 'Interview Guide': 'additional-resources/interview-guide.md'
- How to Maintain This Site: 'development-guidance.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true

# Social
extra:
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/eriktanderson'
    - type: 'github'
      link: 'https://github.com/eanderson-ei'