site_name: EI Metrics
theme: material
nav:
- Home: 'index.md'
- Project Planning:
  - 'Project Planning': 'project-planning/project-planning.md'
- Git:
  - 'Create Project': 'git/initializing-git.md'
- Data Management:
  - 'Database Overview': 'data-management/database-overview.md'