site_name: EI Development Guide
theme: material
nav:
- Home: 'index.md'
- Getting Started:
  - 'Project Planning': getting-started/project-planning.md
- Git:
  - 'Create Project': 'git/initializing-git.md'